/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/companies/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current Company
         * @description The company the request is bound to — what the frontend shell reads first.
         */
        get: operations["current_company_api_v1_companies_current_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness, and the contract version this instance publishes.
         */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/journal-entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Entries
         * @description One page of the company's ledger, in posting order.
         */
        get: operations["list_entries_api_v1_journal_entries_get"];
        put?: never;
        /**
         * Post Entry
         * @description Post one balanced journal entry — retry-safe by its idempotency key.
         */
        post: operations["post_entry_api_v1_journal_entries_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CompanyOut */
        CompanyOut: {
            /** Base Currency */
            base_currency: string;
            /** Code */
            code: string;
            /** Fiscal Year Start Month */
            fiscal_year_start_month: number;
            /** Id */
            id: string;
            /** Name */
            name: string;
        };
        /**
         * ErrorDetail
         * @description The one thing every refusal says: a machine code, a message, the detail.
         */
        ErrorDetail: {
            /** Code */
            code: string;
            /** Details */
            details?: {
                [key: string]: unknown;
            }[] | null;
            /** Message */
            message: string;
        };
        /**
         * ErrorOut
         * @description The one error shape — documented for every endpoint, because every one
         *     answers with it.
         */
        ErrorOut: {
            error: components["schemas"]["ErrorDetail"];
        };
        /** HealthOut */
        HealthOut: {
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /** JournalEntryIn */
        JournalEntryIn: {
            /** Currency */
            currency: string;
            /** Lines */
            lines: components["schemas"]["JournalLineIn"][];
            /** Memo */
            memo?: string | null;
            /**
             * Posting Date
             * Format: date
             */
            posting_date: string;
        };
        /** JournalEntryOut */
        JournalEntryOut: {
            /** Company Id */
            company_id: string;
            /** Currency */
            currency: string;
            /** Id */
            id: string;
            /** Lines */
            lines: components["schemas"]["JournalLineOut"][];
            /**
             * Posting Date
             * Format: date
             */
            posting_date: string;
        };
        /** JournalLineIn */
        JournalLineIn: {
            /** Account */
            account: string;
            /** Credit */
            credit?: string | null;
            /** Debit */
            debit?: string | null;
            /** Party */
            party?: string | null;
        };
        /** JournalLineOut */
        JournalLineOut: {
            /** Account */
            account: string;
            /** Credit */
            credit: string;
            /** Debit */
            debit: string;
            /** Line No */
            line_no: number;
            /** Party */
            party?: string | null;
        };
        /** PageOut */
        PageOut: {
            /** Items */
            items: components["schemas"]["JournalEntryOut"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    current_company_api_v1_companies_current_get: {
        parameters: {
            query?: never;
            header: {
                "x-company-id": string;
                "x-actor"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyOut"];
                };
            };
            /** @description The request could not be understood */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description The caller is not identified */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description The caller may not do this */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description The company, document or route does not exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description The request clashes with one already made */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description The request did not match the contract, or a domain rule refused it */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description The platform failed unexpectedly */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
            /** @description The request could not be understood */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description The caller is not identified */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description The caller may not do this */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description The company, document or route does not exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description The request clashes with one already made */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description The request did not match the contract, or a domain rule refused it */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description The platform failed unexpectedly */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    list_entries_api_v1_journal_entries_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header: {
                "x-company-id": string;
                "x-actor"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageOut"];
                };
            };
            /** @description The request could not be understood */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description The caller is not identified */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description The caller may not do this */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description The company, document or route does not exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description The request clashes with one already made */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description The request did not match the contract, or a domain rule refused it */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description The platform failed unexpectedly */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    post_entry_api_v1_journal_entries_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
                "x-company-id": string;
                "x-actor"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JournalEntryIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JournalEntryOut"];
                };
            };
            /** @description The request could not be understood */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description The caller is not identified */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description The caller may not do this */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description The company, document or route does not exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description The request clashes with one already made */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description The request did not match the contract, or a domain rule refused it */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description The platform failed unexpectedly */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
}
